# Agenda

1. Weight and Height columns unit change
2. Value, Release Clause columns unit transformation

# Pre-Cleaning

In [111]:
import numpy as np
import pandas as pd

In [112]:
teams = pd.read_csv('teams_fifa23.csv')
players = pd.read_csv('players_fifa23.csv')

In [113]:
teams.head()

,ID,Name,League,LeagueId,Overall,Attack,Midfield,Defence,TransferBudget,DomesticPrestige,IntPrestige,Players,StartingAverageAge,AllTeamAverageAge
0,1943,AFC Bournemouth,English Premier League (1),13,74,75,73,73,0,2,1,28,25.8,25.5
1,116418,AFC Richmond,English Premier League (1),13,78,81,79,77,0,5,3,19,27.3,27.3
2,1,Arsenal,English Premier League (1),13,80,83,81,79,0,7,7,29,24.1,23.0
3,2,Aston Villa,English Premier League (1),13,79,79,78,80,0,5,3,32,25.8,25.2
4,1925,Brentford,English Premier League (1),13,75,75,74,75,0,1,1,30,25.4,24.2

In [114]:
players.head()

,ID,Name,FullName,Age,Height,Weight,PhotoUrl,Nationality,Overall,Potential,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,158023,L. Messi,Lionel Messi,35,169,67,https://cdn.sofifa.net/players/158/023/23_60.png,Argentina,91,91,...,91,88,91,67,66,67,62,53,62,22
1,165153,K. Benzema,Karim Benzema,34,185,81,https://cdn.sofifa.net/players/165/153/23_60.png,France,91,91,...,89,84,89,67,67,67,63,58,63,21
2,188545,R. Lewandowski,Robert Lewandowski,33,185,81,https://cdn.sofifa.net/players/188/545/23_60.png,Poland,91,91,...,86,83,86,67,69,67,64,63,64,22
3,192985,K. De Bruyne,Kevin De Bruyne,31,181,70,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,91,91,...,91,91,91,82,82,82,78,72,78,24
4,231747,K. Mbappé,Kylian Mbappé,23,182,73,https://cdn.sofifa.net/players/231/747/23_60.png,France,91,95,...,92,84,92,70,66,70,66,57,66,21

# Data Cleaning


Weight (kg --> lbs)

Height (cm --> feet)

In [115]:
players_copy = players.copy()
players_copy

,ID,Name,FullName,Age,Height,Weight,PhotoUrl,Nationality,Overall,Potential,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,158023,L. Messi,Lionel Messi,35,169,67,https://cdn.sofifa.net/players/158/023/23_60.png,Argentina,91,91,...,91,88,91,67,66,67,62,53,62,22
1,165153,K. Benzema,Karim Benzema,34,185,81,https://cdn.sofifa.net/players/165/153/23_60.png,France,91,91,...,89,84,89,67,67,67,63,58,63,21
2,188545,R. Lewandowski,Robert Lewandowski,33,185,81,https://cdn.sofifa.net/players/188/545/23_60.png,Poland,91,91,...,86,83,86,67,69,67,64,63,64,22
3,192985,K. De Bruyne,Kevin De Bruyne,31,181,70,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,91,91,...,91,91,91,82,82,82,78,72,78,24
4,231747,K. Mbappé,Kylian Mbappé,23,182,73,https://cdn.sofifa.net/players/231/747/23_60.png,France,91,95,...,92,84,92,70,66,70,66,57,66,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,243725,D. Collins,Darren Collins,21,174,68,https://cdn.sofifa.net/players/243/725/23_60.png,Republic of Ireland,47,56,...,50,44,50,41,38,41,40,36,40,15
18535,261933,Yang Dejiang,Dejiang Yang,17,175,60,https://cdn.sofifa.net/players/261/933/23_60.png,China PR,47,57,...,45,45,45,47,48,47,49,49,49,15
18536,267823,L. Mullan,Liam Mullan,18,170,65,https://cdn.sofifa.net/players/267/823/23_60.png,Northern Ireland,47,67,...,52,49,52,46,44,46,46,42,46,17
18537,267824,D. McCallion,Daithí McCallion,17,178,65,https://cdn.sofifa.net/players/267/824/23_60.png,Republic of Ireland,47,61,...,33,33,33,44,42,44,47,49,47,15
18538,261424,N. Rabha,Nabin Rabha,25,176,66,https://cdn.sofifa.net/players/261/424/23_60.png,India,47,50,...,44,40,44,46,43,46,47,47,47,19

In [116]:
#MUST REFRESH THE dataset COPY code before running this section of CODE!!!

lbslist = []
for weight in players_copy['Weight']:
    weight = weight * 2.2046
    weight = round(weight,0)
    weight = f"{weight} lbs"
    lbslist.append(weight)
    
players_copy['Weight'] = lbslist

In [117]:
#MUST REFRESH THE dataset COPY code before running this section of CODE!!!

ftlist = []
for height in players_copy['Height']:
    inches = height/2.54
    feet = inches/12
    ft_height = int(feet)
    in_height = round(inches - (ft_height*12))
    if ((ft_height == 5) and (in_height == 12)):
        ft_height = 6
        in_height = 0
    height = f"{ft_height}' {in_height}"
    ftlist.append(height)

players_copy['Height'] = ftlist

Renaming Height and Weight column names

In [118]:
players_copy = players_copy.rename({'Height':'Height (ft)','Weight':'Weight (lbs)'},axis = 'columns')
players_copy.head()

,ID,Name,FullName,Age,Height (ft),Weight (lbs),PhotoUrl,Nationality,Overall,Potential,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,158023,L. Messi,Lionel Messi,35,5' 7,148.0 lbs,https://cdn.sofifa.net/players/158/023/23_60.png,Argentina,91,91,...,91,88,91,67,66,67,62,53,62,22
1,165153,K. Benzema,Karim Benzema,34,6' 1,179.0 lbs,https://cdn.sofifa.net/players/165/153/23_60.png,France,91,91,...,89,84,89,67,67,67,63,58,63,21
2,188545,R. Lewandowski,Robert Lewandowski,33,6' 1,179.0 lbs,https://cdn.sofifa.net/players/188/545/23_60.png,Poland,91,91,...,86,83,86,67,69,67,64,63,64,22
3,192985,K. De Bruyne,Kevin De Bruyne,31,5' 11,154.0 lbs,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,91,91,...,91,91,91,82,82,82,78,72,78,24
4,231747,K. Mbappé,Kylian Mbappé,23,6' 0,161.0 lbs,https://cdn.sofifa.net/players/231/747/23_60.png,France,91,95,...,92,84,92,70,66,70,66,57,66,21

Player Value and Release Clause unit transformation

In [121]:
#VALUE UNIT TRANSFORMATION
#MUST REFRESH THE dataset COPY code before running this section of CODE!!!

millionlist = []
for value in players_copy['ValueEUR']:
    value = value/1000000
    value = f"{value} mil"
    millionlist.append(value)
    
players_copy['ValueEUR'] = millionlist

In [122]:
players_copy['ValueEUR'].head()

0     54.0 mil
1     64.0 mil
2     84.0 mil
3    107.5 mil
4    190.5 mil
Name: ValueEUR, dtype: object

In [125]:
#RELEASE CLAUSE TRANSFORMATION
#MUST REFRESH THE dataset COPY code before running this section of CODE!!!

releaseclause = []
for clause in players_copy['ReleaseClause']:
    if clause > 999999999:
        clause = round(clause / 100000000,1)
        clause = f"{clause} bil" 
    else:
        clause = round(clause/1000000,1)
        clause = f"{clause} mil"
    releaseclause.append(clause)

players_copy['ReleaseClause'] = releaseclause

In [126]:
players_copy['ReleaseClause']

0         99.9 mil
1        131.2 mil
2        172.2 mil
3        198.9 mil
4        366.7 mil
           ...
18534      0.2 mil
18535      0.2 mil
18536      0.3 mil
18537      0.2 mil
18538      0.1 mil
Name: ReleaseClause, Length: 18539, dtype: object